repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 45ef068da5f21267bb2a7ec4a623092959f09ce5  # frozen: v0.14.14
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'a66e98df7b4aeeb3724184b332785976d062b92e'  # frozen: v1.19.1
    hooks:
      - id: mypy
        args: [ --explicit-package-bases ]
        files: ^packages/
